name: ShadowVim

options:
  bundleIdPrefix: menu.mickael
  createIntermediateGroups: true

packages:
  ShadowVim:
    path: .

targets:
  ShadowVim:
    type: application
    platform: macOS
    deploymentTarget: "13.0"
    sources: [Sources/ShadowVim]
    settings:
      GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - package: ShadowVim
        product: Nvim
