name: ShadowVim

options:
  bundleIdPrefix: menu.mickael
  createIntermediateGroups: true

packages:
  ShadowVim:
    path: .
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.0.0

targets:
  ShadowVim:
    type: application
    platform: macOS
    deploymentTarget: 13.0
    sources: [Sources/ShadowVim]
    settings:
      CURRENT_PROJECT_VERSION: 1
      MARKETING_VERSION: 0.1.0
      INFOPLIST_FILE: Sources/ShadowVim/ShadowVim-Info.plist
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${SV_DEVELOPMENT_TEAM}
      ENABLE_HARDENED_RUNTIME: YES
      DEAD_CODE_STRIPPING: YES
    dependencies:
      - package: ShadowVim
        product: AX
      - package: ShadowVim
        product: Mediator
      - package: ShadowVim
        product: Nvim
      - package: ShadowVim
        product: NSLoggerAdapter
      - package: ShadowVim
        product: SauceAdapter
      - package: Sparkle
        product: Sparkle
