name: Bug report
description: File a bug report to help improve ShadowVim.
body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: Check if applicable
      description: |
        :warning: My time is limited and if I don't plan on fixing the reported bug myself, I might close this issue. No hard feelings.
        :heart: But if you would like to contribute a fix yourself, **I'll be happy to guide you through the codebase and review a pull request**.
      options:
        - label: I have searched the existing issues (**required**)
          required: true
        - label: I reproduced the issue with an empty Neovim configuration (`init.vim` or `init.lua`)
          required: true
        - label: I'm willing to help fix the problem and contribute a pull request
  - type: textarea
    id: bug-description
    attributes:
      label: Describe the bug
      description: Also tell me, what did you expect to happen?
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: bug-steps
    attributes:
      label: How to reproduce?
      description: |
        Step by step explanation to reproduce the issue.

        If you can, drag and drop:
        - a zipped sample project
        - screenshots or a [screencast](https://support.apple.com/lv-lv/guide/quicktime-player/qtp97b08e666/mac) showing the issue
      placeholder: |
        1. Open the file `test.swift`
        2. Go to line `x`
        3. Perform keystrokes `cUaw`
        4. See error
        ...
    validations:
      required: true
  - type: textarea
    id: vim-config
    attributes:
      label: Neovim configuration
      description: |
        Paste the minimal Neovim configuration file (`init.vim` or `init.lua`) reproducing the issue.
      render: viml
    validations:
      required: true
  - type: textarea
    id: bug-environment
    attributes:
      label: Environment
      description: |
        Run the **Copy Debug Info** action from the menu bar icon, then paste its result here.
      placeholder: |
        ShadowVim 0.1.0 (1)

        $ sw_vers -productVersion
        13.2.1
        $ uname -m
        arm64
        $ xcodebuild -version
        Xcode 14.2
        Build version 14C18
        $ nvim --version
        NVIM v0.8.3
      render: bash
