name: Feature request
description: Suggest an idea for this project.
body:
  - type: checkboxes
    id: checks
    attributes:
      label: If you have an idea, create a discussion
      options:
        - label: I understand and will [create a new discussion](https://github.com/mickael-menu/ShadowVim/discussions/new?category=ideas) instead of an issue.

